export const BG_BASED_ON_TYPE: Record<string, string> = {
  bug: '#48d0b0',
  dark: '#e2d7fe',
  dragon: '#e2d7fe',
  electric: '#fff5da',
  fairy: '#fedee7',
  fighting: '#fedee7',
  fire: '#F96555',
  flying: '#eee9fc',
  ghost: '#e4dde8',
  grass: '#2ADAB1',
  ground: '#e4ddda',
  ice: '#e9f7f7',
  monster: '#e4f4ff',
  normal: '#eeeee4',
  poison: '#eddef1',
  psychic: '#fcebee',
  rock: '#f5e6e4',
  steel: '#d6d7d9',
  water: '#58ABF6',
};
